name: logisim-evolution-snapcraft
icon: snap/gui/logisim-icon-128.png
license: GPL-3.0
summary: Logisim is a digital circuit simulator
description: |
  Github (compilation) : https://github.com/anrouxel/logisim-evolution-snapcraft
base: core22
grade: stable
confinement: strict

adopt-info: logisim-evolution-snapcraft

architectures:
  - build-on: amd64
    build-for: amd64

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

apps:
  logisim-evolution-snapcraft:
    extensions: [gnome]
    command: usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH/bin/java -jar $SNAP/logisim/logisim-evolution.jar
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - network

parts:     
  logisim-evolution-snapcraft:
    plugin: nil
    source: https://github.com/logisim-evolution/logisim-evolution.git
    source-type: git
    override-pull: |
      craftctl default
      git checkout develop
      craftctl set version="$(date +%Y%m%d)"
    override-build: |
      # Gets the host and port from a proxy URL
      #   $1 = the proxy URL, such as "http://10.10.10.1:8222/"
      getproxy () {
          # Parses URL with Bash or Dash shell parameter expansion
          tail=${1#http*://}
          head=${tail%%/*}
          host=${head%:*}
          port=${head##*:}
      }
      # Adds Java system properties using shell positional parameters
      set --
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          set -- "$@" "-Dhttp.proxyHost=$host" "-Dhttp.proxyPort=$port"
      fi
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          set -- "$@" "-Dhttps.proxyHost=$host" "-Dhttps.proxyPort=$port"
      fi
      bash gradlew "$@" shadowJar && \
      mkdir $CRAFT_PART_INSTALL/logisim && \
      cd build/libs && \
      mv *-all.jar logisim-evolution.jar && \
      mv logisim-evolution.jar $CRAFT_PART_INSTALL/logisim
    build-packages:
      - git
      - sed
      - openjdk-17-jdk
      - libfontconfig1-dev
    stage-packages:
      - openjdk-17-jre
      - fonts-freefont-ttf
      - fonts-arphic-uming
      - fontconfig-config
